### PR TITLE
Allow the Project Setup Wizard to be exited without creating the project; Fix Project Setup Wizard validation.

### PR DESCRIPTION
**Pull request by swalker1595**
I wanted to allow the user to exit the Project Setup Wizard without creating the project. In doing this, I also decided to fix the Project Setup Wizard validation where a space can be used as the root namespace, causing errors.

To do this, I adjusted SetupWizard.cs to use a loop in the call to inputForm. This loop creates an instance of WizardView, with the default values, the first time it's called. If the user presses _Ok_ the loop calls inputForm.PassesValidation which checks to see that all the values in the form are acceptable. If the user exists the dialog, the loop throws a WizardCancelledException, which causes the project to fail to load.

In the first two commits, I had to adjust the references in the project in order to build the project.

### CODE REVIEW

**Comment by ChrisHammond** [comment]
Thanks! I will take a look at this in the next couple of days and try to get the PR merged in!

**Comment by swalker1595** [comment]
I hope it goes well! I am not sure what was going on with the project references. I had to remove the references to EnvDTE in DNNTemplates.csproj. I also had to copy the packages folder from the VSIX folder into the CSharp-DAL2-MVC-Template and CSharp-DAL2-SPA-Template. However, I did not commit the duplicate package folders.

**Comment by WillStrohl** [comment]
Great stuff!  :)

**Comment by ChrisHammond** [comment]
@shanewalker1595 ever since I merged this PR, I can no longer get the VSIX files to compile. Can you grab the latest from MASTER and see if you can compile?

If I go back to commit aebe3c232a4cce493bafbc0bca342d835b259aad which was my last one from Feb 2017, I can compile just fine. Have tried on multiple machines with VS Community and VS Professional, but am having absolutely no luck and pulling my hair out.

**Comment by swalker1595** [comment]
@ChrisHammond, I experienced the same issue. I narrowed the issue down to change to DNNTemplates.csproj in commit https://github.com/ChrisHammond/DNNTemplates/commit/bbd3018803d77c137ad7878a9513a0985e0ac603#diff-2d8f0ec1f2b7cfd3f58c23ff643511b1

Try rolling back the .csproj to before that commit:

`git reset --hard master`
`git checkout c707261 -- VSIX/DNNTemplates/DNNTemplates.csproj`

The vsix should now build to the release directory.

**Comment by ChrisHammond** [comment]
Thanks Shane I'll give it a try

**Comment by ChrisHammond** [comment]
Yup that was it. Now I remember running into a problem where it would error when compiling,  and removing that line fixed it.

The error relates to the "length" of the path. Thinking I might clean up the naming of the templates to be DNN instead of DotNetNuke to try to save characters.

Thanks again!

**Comment by swalker1595** [comment]
Chris, Thank you for working with me on this! This is actually my first github pull request.

I remember having the issue about length of the path too.

**Comment by ChrisHammond** [comment]
So I had to uncheck the deploy experimental option to get it to build. Will do my final testing tonight and hopefully release today/tomorrow!

**Pull request merged**
